pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'pandoras_creatures'
include 'common'

def fabricOnly = providers.gradleProperty('fabricOnly')
        .map { it.toBoolean() }
        .orElse(false)
        .get()

def forgeOnly = providers.gradleProperty('forgeOnly')
        .map { it.toBoolean() }
        .orElse(false)
        .get()

def neoforgeOnly = providers.gradleProperty('neoforgeOnly')
        .map { it.toBoolean() }
        .orElse(false)
        .get()

def skipForge = providers.gradleProperty('skipForge')
        .map { it.toBoolean() }
        .orElse(false)
        .get()

def skipNeoForge = providers.gradleProperty('skipNeoForge')
        .map { it.toBoolean() }
        .orElse(false)
        .get()

if (!forgeOnly && !neoforgeOnly) {
    include 'fabric'
}

if (!fabricOnly && !neoforgeOnly && !skipForge) {
    include 'forge'
}

if (!fabricOnly && !forgeOnly && !skipNeoForge) {
    include 'neoforge'
}
