pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'pandoras_creatures'
include 'common'
include 'fabric'

def fabricOnly = providers.gradleProperty('fabricOnly')
        .map { it.toBoolean() }
        .orElse(false)
        .get()

if (!fabricOnly) {
    include 'forge'
    include 'neoforge'
}
