plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = rootProject.version
group = rootProject.group
evaluationDependsOn(':common')

base {
    archivesName = "${mod_id}-neoforge-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

sourceSets {
    main {
        java.srcDirs = [project.file('src/main/java')]
        resources.srcDirs = [project.file('src/main/resources'), project.file('src/generated/resources')]
        compileClasspath += project(':common').sourceSets.main.output
        runtimeClasspath += project(':common').sourceSets.main.output
    }
    test {
        java.srcDirs = [project.file('src/test/java')]
        resources.srcDirs = [project.file('src/test/resources')]
        compileClasspath += project(':common').sourceSets.main.output
        runtimeClasspath += project(':common').sourceSets.main.output
    }
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
            gameDirectory = rootProject.layout.projectDirectory.dir('run/client')
        }

        server {
            server()
            gameDirectory = rootProject.layout.projectDirectory.dir('run/server')
            programArgument '--nogui'
        }

        gameTestServer {
            type = "gameTestServer"
            gameDirectory = rootProject.layout.projectDirectory.dir('run/gametest')
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            type = "serverData"
            gameDirectory = rootProject.layout.projectDirectory.dir('run/data')
            systemProperty 'pandoras_creatures.sharedGeneratedClientOutput',
                    rootProject.layout.projectDirectory.dir('common/src/generated/resources').asFile.absolutePath
            systemProperty 'pandoras_creatures.sharedGeneratedWorldgenOutput',
                    rootProject.layout.projectDirectory.dir('common/src/generated/resources').asFile.absolutePath
            programArguments.addAll '--mod', mod_id, '--all',
                    '--output', project.file('src/generated/resources/').getAbsolutePath(),
                    '--existing', project.file('src/main/resources/').getAbsolutePath(),
                    '--existing', rootProject.layout.projectDirectory.dir('common/src/main/resources').asFile.absolutePath,
                    '--existing', rootProject.layout.projectDirectory.dir('common/src/generated/resources').asFile.absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet project(':common').sourceSets.main
            sourceSet sourceSets.main
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    implementation project(':common')
    testImplementation platform('org.junit:junit-bom:5.14.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('jar', Jar).configure {
    from(project(':common').sourceSets.main.output)
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties + [project: project]
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${rootProject.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
